### ISSUE TITLE
day 2: Rob Vettor video and code is missiing

### ISSUE THREAD

**Issue by nomada2** [dotnet-presentations/dotNETConf#19]
can you add: day 2: Rob Vettor video and code?

**Comment by grigast** [comment]
Video is available on MSDN channel9:
https://channel9.msdn.com/Events/dotnetConf/Focus-on-Microservices.

The source is still missing.

**Comment by tebeco** [comment]
Hello,

This question has been raised multiple times during live, on twitter latter on, and here too
Is there any insight on this ? I think it can become frustrating as the answer elvolved during live from "we will in 2 days", then "in a weeks after youtube upload" and then once announced on twitter (latter) "it's already in this repo"

Sorry about that, but I'll try to ping people related to the meeting that might give an official answer to that
I'm not happy to do that, but so far, there's no answer anywhere on the current status, which feels very weird
organizers : @BethMassi  @jongalloway @csharpfritz
speakers :@robvet @robvettor @monubamb

**Comment by BethMassi** [comment]
Totally understand the frustration here. We've contacted the speakers and asked for an update. They were planning on building out a GitHub repo for this.

**Comment by tebeco** [comment]
wow amazing news

thx a lot @BethMassi for the quick reply

again I apologize for pinging everyone.
Being in the dark make time flies slower ;)

**Comment by robvet** [comment]
Hello tebeco... Have started several times on twitter that we are working through a number of unplanned issues releasing the reference code. Understand your frustratiion and please accept our apologies. We're not ignoring or forgetting about you. Follow me @robvettor and I will keep you updated. In the meantime, take a look at this lab which uses another Microsoft reference application, entitled eShopOnContainers: https://docs.microsoft.com/en-us/learn/modules/microservices-aspnet-core/2-deploy-application. Our reference app from .NET Conf was closely modeled after the eShop app.

**Comment by tebeco** [comment]
> Have started several times on twitter that we are working through a number of unplanned issues releasing the reference code

Welp my bad, it seems I missed that one :(
I effectivly notice previous tweet about `eShopContainers` (thx for that other link ^^)

As said, I'm not proud of piging like this, but as [this repo was poitned](https://twitter.com/csharpfritz/status/1297280640602247179)
I though having it here would probably help other developpers, as Twitter is not the best "platform to search for old tweets"

I now see your tweet from yesterday https://twitter.com/robvettor/status/1304603585544626176?s=20

**Comment by robvet** [comment]
TeBeCo…

Completely agree. And, it’s all good, man.

Again our apologies for the delay on the source code. Working through some unexpected blockers. You know, man, it’s always something.

Thanks for your input.

Rob Vettor  | Principal Cloud-Native Application Architect
                      | SSG IP Architect
                      | Microsoft Certified Trainer
                      | CNCF (Cloud-Native Computing Foundation) Speaker Bureau<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.cncf.io%2Fspeaker%2Frobvet%2F&data=02%7C01%7Crobvet%40microsoft.com%7C4f91ec2c80f148e1d8df08d7cf475847%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637205777651526225&sdata=CrbTGz%2BmGfvfff25gczEOBjRRon13Vo0LmRA7UZQ5tE%3D&reserved=0>
                      | Owner: Microservices with Containers WorkshopPLUS

[cid:image001.jpg@01D68933.E8E5CCC0]   [cid:image002.jpg@01D68933.E8E5CCC0]

[cid:image003.gif@01D68933.E8E5CCC0]  214-707-0584
[cid:image004.gif@01D68933.E8E5CCC0]   robvet@microsoft.com<mailto:robvet@microsoft.com>
[cid:image005.jpg@01D68933.E8E5CCC0]  www.thinkingincloudnative.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.thinkingincloudnative.com%2F&data=02%7C01%7Crobvet%40microsoft.com%7C4f91ec2c80f148e1d8df08d7cf475847%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637205777651536180&sdata=A8J9SmdjhA%2BDXPMWSfoBy4QK8JuPeIGF8jV%2FWqfngVI%3D&reserved=0>

Co-Author of…
[cid:image006.png@01D68933.E8E5CCC0]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdotnet%2Farchitecture%2Fcloud-native%2F&data=02%7C01%7Crobvet%40microsoft.com%7C4f91ec2c80f148e1d8df08d7cf475847%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637205777651536180&sdata=krj4OY1RJX3KfByGp2BrYDXBR%2BWcDNvJ0xpMzXhGhqc%3D&reserved=0>

**Comment by BethMassi** [comment]
We'll work on some solutions and keep this issue posted.

**Comment by tebeco** [comment]
@jongalloway can you share the link it as well for anyone looking for it ?

**Comment by nomada2** [comment]
i think the issue is still open
