### ISSUE TITLE
.NET Purple Theme for Visual Studio?

### ISSUE THREAD

**Issue by cgtyoder** [dotnet-presentations/dotNETConf#29]
Any plans on making this compatible with Visual Studio?

**Comment by jomustech** [comment]
Hi @cgtyoder ,

It's been a while, did you check again? I have installed it on my own and it works fine (Win 10, latest version of VS) https://focus.dotnetconf.net/

**Comment by PranamBhat** [comment]
Hi @cgtyoder 

Here is the **.NET Purple Theme** for **Visual Studio**:

[https://marketplace.visualstudio.com/items?itemName=dotnetconfteam.dotnet-purple-theme](https://marketplace.visualstudio.com/items?itemName=dotnetconfteam.dotnet-purple-theme)

**Comment by cgtyoder** [comment]
AFAICT this is only compatible with VS Code, not Visual Studio (2019). If you can tell me how to install in VS, that would be great.

**Comment by PranamBhat** [comment]
Hi @cgtyoder 

Go to **Visual Studio** > **Marketplace** and search for the purple theme :

[https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple)

[http://orta.io/vscode-themes/](http://orta.io/vscode-themes/)

[https://marketplace.visualstudio.com/items?itemName=thegeoffstevens.best-colorful-themes-pack](https://marketplace.visualstudio.com/items?itemName=thegeoffstevens.best-colorful-themes-pack)


Try any of these by searching "**Purple Theme**" on the "**Marketplace**" and click on "**Install**".

Once it is completed, close the **Visual Studio** and "**Restart**" the system.


**Thank you!**

**Comment by augustoproiete** [comment]
@PranamBhat All the themes you linked are for Visual Studio **Code** - Not for **Visual Studio**. They are completely separate products.

![image](https://user-images.githubusercontent.com/177608/109265574-25c3d180-77dd-11eb-8f3b-19cf9a82365d.png)

This is how Visual Studio 2019 looks like today:

![image](https://user-images.githubusercontent.com/177608/109265667-49871780-77dd-11eb-89ac-e07575a2a098.png)

**Comment by PranamBhat** [comment]
Hi @augustoproiete 

Can you check this one and set the theme :


[https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-personalize-the-ide?view=vs-2019](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-personalize-the-ide?view=vs-2019)


[https://docs.microsoft.com/en-us/visualstudio/ide/how-to-change-fonts-and-colors-in-visual-studio?view=vs-2019](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-change-fonts-and-colors-in-visual-studio?view=vs-2019)

**Comment by PranamBhat** [comment]
Also, try this one : [https://stackoverflow.com/questions/14050561/microsoft-visual-studio-change-default-theme](https://stackoverflow.com/questions/14050561/microsoft-visual-studio-change-default-theme)

**Comment by michaelbkanobi** [comment]
There’s a theme converter for VS 2022
https://devblogs.microsoft.com/visualstudio/vs-code-themes-in-vs/
