### ISSUE TITLE
When keynote demo will be available ?

### ISSUE THREAD

**Issue by navneetgarggate6** [dotnet-presentations/dotNETConf#51]
Keynote
Scott Hunter Daniel Roth Maria Naggaga Mads Torgersen Maddy Leger Montaquila

Join Scott Hunter and team as they show you all the amazing things you can do with .NET 6.

Slides
Video
Demo (coming soon!)

**Comment by BethMassi** [comment]
Just added a link to it. We announced it yesterday. Enjoy!

https://github.com/microsoft/dotnet-podcasts

**Comment by navneetgarggate6** [comment]
Thank you very much.
