### ISSUE TITLE
Question about using Keynote images at local .net conf?

### ISSUE THREAD

**Issue by shyunMin** [dotnet-presentations/dotNETConf#53]
Hello, I am Min working at Samsung.
I am preparing a session at .NET Conf 2022 x Seoul about Introducing MAUI.
I went through the contents here to prepare my session and I would like to use some images related to maui and maui blazor that are in Keynote slide deck 27 and 28.
Is it allowed to edit those images and use on my slide deck?
Just want to make sure there is no license issue.
Thanks

**Comment by BethMassi** [comment]
Yes it's absolutely okay to use these slides publicly. Please convey similar messages as the talk track. You might also want to pull in slide 24 to set up Blazor depending on your storytelling. Thank you for spreading the good word about .NET!
