### ISSUE TITLE
Digital pet for Visual Studio

### ISSUE THREAD

**Issue by SebastianJust** [dotnet-presentations/dotNETConf#67]
Hello,

Are there any hope for digital pets for Visual Studio as well? :) It's very nice!

**Comment by mairaw** [comment]
You mean like the .NET bot?

**Comment by csharpfritz** [comment]
Digital pets are an extension created by a member of the community for Visual Studio Code.

You will need to contact the owner of that project at https://github.com/tonybaloney/vscode-pets
