### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to fetch

### ISSUE THREAD

**Issue by mbiesiad** [dotnet-presentations/dotNETConf#68]
# Description / Current behavior:
`Uncaught (in promise) TypeError: Failed to fetch` occurs for site `https://www.dotnetconf.net`

# Expected behavior
No mentioned error (handled error).

# Steps to replicate
1. Go to: https://www.dotnetconf.net/
2. Check DevTools Console
3. See `Uncaught (in promise) TypeError: Failed to fetch`

# Additional information
Browser: Brave
OS: Windows 10
For Firefox and Chrome works fine - doesn't occur.

Screenshot:
![image](https://user-images.githubusercontent.com/18367606/200667476-287e740b-0262-4863-ae89-4cde0b7694c4.png)

Best wishes,

**Comment by csharpfritz** [comment]
no issue found
