### ISSUE TITLE
there is no code posted

### ISSUE THREAD

**Issue by ArtistShare** [dotnet-presentations/dotNETConf#72]
I came here from YouTube from the ML.NET: Machine learning from data to production in less than 30 minutes video (which is great).  The link to GitHub code page brought me here.   It also says code is available in heading but there are no links to code.  Please let me know where I can get code for ML.NET: Machine learning from data to production in less than 30 minutes video examples.  Thanks!

**Comment by mairaw** [comment]
@luisquintanilla do you know where that code would be? In the YouTube description it says code and slides would be here, but I only see the slides as well.

**Comment by luisquintanilla** [comment]
Hi @ArtistShare,

Apologies for the confusion. I don't think that code was ever published. However, we do have several tutorials and examples you might find useful. 

- [Tutorial: Predict prices using regression with Model Builder](https://learn.microsoft.com/en-us/dotnet/machine-learning/tutorials/predict-prices-with-model-builder) - one of the many tutorials available in our docs.
- [Machine Learning Samples Repo](https://github.com/dotnet/machinelearning-samples/tree/main)

I would recommend starting with the Model Builder samples in our docs. Hope that helps.

**Comment by mairaw** [comment]
Thanks @luisquintanilla. I also updated the video description to just say slides.
