### ISSUE TITLE
2023 .NET Conf swag form 404

### ISSUE THREAD

**Issue by ijat** [dotnet-presentations/dotNETConf#77]
Hello, I don't know where to report the issue. Sorry if this the wrong place but i dont see any contact form there.

So the issue is I tried to register the https://www.dotnetconf.net/swag using the form and clicked Submit, but the GET request returns 404.
![image](https://github.com/dotnet-presentations/dotNETConf/assets/6663845/a0c119e4-5f96-46d9-9068-a233b477c769)

**Comment by jglozano** [comment]
Thanks for letting us know! This has been fixed.
