### ISSUE TITLE
2023 Slides

### ISSUE THREAD

**Issue by karoldeland** [dotnet-presentations/dotNETConf#83]
Hi, 
Is there a chance we'll get access to slides from this year real soon? We are a lot to organize local events and we still don't have technical material to use. 

Thanks!

**Comment by csharpfritz** [comment]
There are a bunch of slides from the 2023 event available in https://github.com/dotnet-presentations/dotNETConf/tree/main/2023/Technical 

We're adding more as we receive them

**Comment by karoldeland** [comment]
Thanks for the quick reply @csharpfritz 
Core presentations are missing imho. Do you have an ETA?

Thanks!

**Comment by jongalloway** [comment]
@karoldeland We're processing them, many need to be edited to get them under 25mb for GitHub. If there are specific sessions you are looking for we can prioritize them.

**Comment by karoldeland** [comment]
Slides for Building Cloud Native Apps with .NET 8 are now available. Thanks.
